### ISSUE TITLE
Design & implement auth proxy of api-server

### ISSUE THREAD

**Issue by maslow** [labring/laf-roadmap#4]
## Summary

Usually, the `api-server` in the kubernetes cluster only supports the `cert-signing` method for user authentication by default, which means that we need to access the `api-server` through a `kubeconfig` containing the user certificate.

However, self-signed certificates cannot be used to sign requests in the web environment, so we need to find a way to make `api-server` accessible to web clients without invading the api-server.

## Intended Outcome

We have found a project that already implemented the idea above.

- https://github.com/fengxsong/vmdashboard

## How will it work?

 We plan to add an `auth proxy` between the web and `api-server`, so the request path will like that:

```mermaid
sequenceDiagram
    participant web as WebConsole
    participant ap as AuthProxy
    participant kas as KubeAPIServer
    web->>ap: http request with jwt token
    ap->>kas: replace jwt with kubeconfig and then request
```

> ❓ Does the `auth proxy` need to generate kubeconfig for jwt user?

## TODO

- [ ] Ask for the author how can we use vmdashboard source
- [ ] Build the docker image for vmdashboard
- [ ] Build the sealos image for vmdashboard

## References

- https://github.com/fengxsong/vmdashboard

**Comment by maslow** [comment]
Temporarily use the same solution as sealos, using the kubeconfig call in next.js. This issue is closed first.
